### ISSUE TITLE
Nitpick: literal newline in `fabric.mod.json` of 1.2.0 for 1.20.4 artifact

### ISSUE THREAD

**Issue by YoshiRulz** [iChun/BetterThanLlamas#8]
This doesn't seem to be a problem for the Fabric loader, but a strict parser like `jq`'s will choke on literal newlines in strings.
Since it's not literal in the source:
https://github.com/iChun/BetterThanLlamas/blob/fbd80b7f07d2b9446287bd2ba8c5469397a92af4/src/main/resources/fabric.mod.json#L7
...I'm guessing the process of expanding templates is what introduces it.

**Comment by iChun** [comment]
I was wondering what specifically your use case for `jq` was? I'm not very sure how I would otherwise put a new line into the description of the mod in fabric.mod.json, and alternatives for jq was to [run the file through sed](https://stackoverflow.com/questions/32715008/jq-how-to-print-newline-and-not-newline-character-from-json-value) first, which is really all I could kinda find about the topic.

Happy to hear if you have any suggestions/workarounds for the matter

**Comment by YoshiRulz** [comment]
see FabricMC/fabric-example-mod#282

**Comment by iChun** [comment]
Had a tinker with what you've sent and couldn't find anything that worked. I had a look at the compiled `fabric.mod.json` and I  get what broke now 😂 

I've managed to muck up something that might work and leaves the entire description intact in one line, would this be okay with you?

**Comment by YoshiRulz** [comment]
Well removing the newline also works, yeah. You just need to use '\\n` if you want one.

**Comment by iChun** [comment]
[fabric.mod.json](https://github.com/iChun/BetterThanLlamas/files/15370917/fabric.mod.json)

This is the file gradle spat out after building, just checking with you to make sure it's all okay on your end
